export const player = {
	player: {
		id: 627,
		name: 'K. Walker',
		firstname: 'Kyle',
		lastname: 'Walker',
		age: 31,
		birth: {
			date: '1990-05-28',
			place: 'Sheffield',
			country: 'England',
		},
		nationality: 'England',
		height: '178 cm',
		weight: '70 kg',
		injured: false,
		photo: 'https://media.api-sports.io/football/players/627.png',
	},
	statistics: [
		{
			team: {
				id: 50,
				name: 'Manchester City',
				logo: 'https://media.api-sports.io/football/teams/50.png',
			},
			league: {
				id: 39,
				name: 'Premier League',
				country: 'England',
				logo: 'https://media.api-sports.io/football/leagues/39.png',
				flag: 'https://media.api-sports.io/flags/gb.svg',
				season: 2020,
			},
			games: {
				appearences: 24,
				lineups: 22,
				minutes: 1946,
				number: null,
				position: 'Defender',
				rating: '6.866666',
				captain: false,
			},
			substitutes: {
				in: 2,
				out: 2,
				bench: 11,
			},
			shots: {
				total: 6,
				on: 3,
			},
			goals: {
				total: 1,
				conceded: 0,
				assists: 1,
				saves: null,
			},
			passes: {
				total: 1733,
				key: 8,
				accuracy: 65,
			},
			tackles: {
				total: 29,
				blocks: 7,
				interceptions: 14,
			},
			duels: {
				total: 172,
				won: 91,
			},
			dribbles: {
				attempts: 41,
				success: 24,
				past: null,
			},
			fouls: {
				drawn: 11,
				committed: 25,
			},
			cards: {
				yellow: 1,
				yellowred: 0,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: 0,
				missed: 0,
				saved: null,
			},
		},
		{
			team: {
				id: 50,
				name: 'Manchester City',
				logo: 'https://media.api-sports.io/football/teams/50.png',
			},
			league: {
				id: 45,
				name: 'FA Cup',
				country: 'England',
				logo: 'https://media.api-sports.io/football/leagues/45.png',
				flag: 'https://media.api-sports.io/flags/gb.svg',
				season: 2020,
			},
			games: {
				appearences: 3,
				lineups: 3,
				minutes: 270,
				number: null,
				position: 'Defender',
				rating: '7.233333',
				captain: false,
			},
			substitutes: {
				in: 0,
				out: 0,
				bench: 1,
			},
			shots: {
				total: 1,
				on: 1,
			},
			goals: {
				total: 1,
				conceded: 0,
				assists: null,
				saves: null,
			},
			passes: {
				total: 338,
				key: 2,
				accuracy: 106,
			},
			tackles: {
				total: 1,
				blocks: null,
				interceptions: 6,
			},
			duels: {
				total: 16,
				won: 8,
			},
			dribbles: {
				attempts: 5,
				success: 4,
				past: null,
			},
			fouls: {
				drawn: 2,
				committed: 1,
			},
			cards: {
				yellow: 1,
				yellowred: 0,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: 0,
				missed: 0,
				saved: null,
			},
		},
		{
			team: {
				id: 50,
				name: 'Manchester City',
				logo: 'https://media.api-sports.io/football/teams/50.png',
			},
			league: {
				id: 48,
				name: 'League Cup',
				country: 'England',
				logo: 'https://media.api-sports.io/football/leagues/48.png',
				flag: 'https://media.api-sports.io/flags/gb.svg',
				season: 2020,
			},
			games: {
				appearences: 4,
				lineups: 3,
				minutes: 259,
				number: null,
				position: 'Defender',
				rating: '7.075000',
				captain: false,
			},
			substitutes: {
				in: 1,
				out: 1,
				bench: 2,
			},
			shots: {
				total: null,
				on: null,
			},
			goals: {
				total: 0,
				conceded: 0,
				assists: null,
				saves: null,
			},
			passes: {
				total: 212,
				key: 3,
				accuracy: 49,
			},
			tackles: {
				total: 4,
				blocks: null,
				interceptions: 4,
			},
			duels: {
				total: 18,
				won: 12,
			},
			dribbles: {
				attempts: 1,
				success: 1,
				past: null,
			},
			fouls: {
				drawn: 3,
				committed: 3,
			},
			cards: {
				yellow: 0,
				yellowred: 0,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: 0,
				missed: 0,
				saved: null,
			},
		},
		{
			team: {
				id: 50,
				name: 'Manchester City',
				logo: 'https://media.api-sports.io/football/teams/50.png',
			},
			league: {
				id: 2,
				name: 'UEFA Champions League',
				country: 'World',
				logo: 'https://media.api-sports.io/football/leagues/2.png',
				flag: null,
				season: 2020,
			},
			games: {
				appearences: 11,
				lineups: 11,
				minutes: 982,
				number: null,
				position: 'Defender',
				rating: '7.100000',
				captain: false,
			},
			substitutes: {
				in: 0,
				out: 1,
				bench: 1,
			},
			shots: {
				total: 2,
				on: 1,
			},
			goals: {
				total: 0,
				conceded: 0,
				assists: null,
				saves: null,
			},
			passes: {
				total: 771,
				key: 3,
				accuracy: 62,
			},
			tackles: {
				total: 23,
				blocks: 1,
				interceptions: 14,
			},
			duels: {
				total: 78,
				won: 50,
			},
			dribbles: {
				attempts: 16,
				success: 11,
				past: null,
			},
			fouls: {
				drawn: 2,
				committed: 7,
			},
			cards: {
				yellow: 1,
				yellowred: 0,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: 0,
				missed: 0,
				saved: null,
			},
		},
		{
			team: {
				id: 10,
				name: 'England',
				logo: 'https://media.api-sports.io/football/teams/10.png',
			},
			league: {
				id: 5,
				name: 'UEFA Nations League',
				country: 'World',
				logo: 'https://media.api-sports.io/football/leagues/5.png',
				flag: null,
				season: 2020,
			},
			games: {
				appearences: 5,
				lineups: 5,
				minutes: 404,
				number: null,
				position: 'Defender',
				rating: '6.740000',
				captain: false,
			},
			substitutes: {
				in: 0,
				out: 1,
				bench: 0,
			},
			shots: {
				total: 1,
				on: null,
			},
			goals: {
				total: 0,
				conceded: 0,
				assists: null,
				saves: null,
			},
			passes: {
				total: 358,
				key: 1,
				accuracy: 64,
			},
			tackles: {
				total: 3,
				blocks: 2,
				interceptions: 3,
			},
			duels: {
				total: 19,
				won: 12,
			},
			dribbles: {
				attempts: 5,
				success: 4,
				past: null,
			},
			fouls: {
				drawn: 1,
				committed: 4,
			},
			cards: {
				yellow: 2,
				yellowred: 1,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: 0,
				missed: 0,
				saved: null,
			},
		},
		{
			team: {
				id: 10,
				name: 'England',
				logo: 'https://media.api-sports.io/football/teams/10.png',
			},
			league: {
				id: null,
				name: 'EC Qualification',
				country: null,
				logo: null,
				flag: null,
				season: '2020',
			},
			games: {
				appearences: 2,
				lineups: 2,
				minutes: 180,
				number: null,
				position: 'Defender',
				rating: '6.925000',
				captain: false,
			},
			substitutes: {
				in: 0,
				out: 0,
				bench: 0,
			},
			shots: {
				total: 0,
				on: 0,
			},
			goals: {
				total: 0,
				conceded: 0,
				assists: null,
				saves: null,
			},
			passes: {
				total: 226,
				key: 0,
				accuracy: 62,
			},
			tackles: {
				total: 1,
				blocks: 0,
				interceptions: 3,
			},
			duels: {
				total: 23,
				won: 14,
			},
			dribbles: {
				attempts: 3,
				success: 2,
				past: null,
			},
			fouls: {
				drawn: 3,
				committed: 1,
			},
			cards: {
				yellow: 0,
				yellowred: 0,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: 0,
				missed: 0,
				saved: null,
			},
		},
		{
			team: {
				id: 10,
				name: 'England',
				logo: 'https://media.api-sports.io/football/teams/10.png',
			},
			league: {
				id: 10,
				name: 'Friendlies',
				country: 'World',
				logo: 'https://media.api-sports.io/football/leagues/10.png',
				flag: null,
				season: 2020,
			},
			games: {
				appearences: 0,
				lineups: 0,
				minutes: 0,
				number: null,
				position: 'Defender',
				rating: null,
				captain: false,
			},
			substitutes: {
				in: 0,
				out: 0,
				bench: 0,
			},
			shots: {
				total: null,
				on: null,
			},
			goals: {
				total: 0,
				conceded: null,
				assists: null,
				saves: null,
			},
			passes: {
				total: null,
				key: null,
				accuracy: null,
			},
			tackles: {
				total: null,
				blocks: null,
				interceptions: null,
			},
			duels: {
				total: null,
				won: null,
			},
			dribbles: {
				attempts: null,
				success: null,
				past: null,
			},
			fouls: {
				drawn: null,
				committed: null,
			},
			cards: {
				yellow: 0,
				yellowred: 0,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: null,
				missed: null,
				saved: null,
			},
		},
		{
			team: {
				id: 10,
				name: 'England',
				logo: 'https://media.api-sports.io/football/teams/10.png',
			},
			league: {
				id: 4,
				name: 'Euro Championship',
				country: 'World',
				logo: 'https://media.api-sports.io/football/leagues/4.png',
				flag: null,
				season: 2020,
			},
			games: {
				appearences: 4,
				lineups: 4,
				minutes: 360,
				number: null,
				position: 'Defender',
				rating: '6.925000',
				captain: false,
			},
			substitutes: {
				in: 0,
				out: 0,
				bench: 0,
			},
			shots: {
				total: 0,
				on: 0,
			},
			goals: {
				total: 0,
				conceded: 0,
				assists: null,
				saves: null,
			},
			passes: {
				total: 226,
				key: 0,
				accuracy: 62,
			},
			tackles: {
				total: 1,
				blocks: 0,
				interceptions: 3,
			},
			duels: {
				total: 23,
				won: 14,
			},
			dribbles: {
				attempts: 3,
				success: 2,
				past: null,
			},
			fouls: {
				drawn: 3,
				committed: 1,
			},
			cards: {
				yellow: 0,
				yellowred: 0,
				red: 0,
			},
			penalty: {
				won: null,
				commited: null,
				scored: 0,
				missed: 0,
				saved: null,
			},
		},
	],
};
